### ISSUE TITLE
[Bug]: Need to remove trim the `/` for the `TURBO_API`

### ISSUE THREAD

**Issue by shunkakinoki** [AdiRishi/turborepo-remote-cache-cloudflare#144]
Thank you @AdiRishi for such a wonderful contribution :) 

For anyone seeing this, adding the slash or `/` at the end will cause the API to fail

ex) `https://YOUR_WRANGLER_NAME.wrangler.dev/` -> `https://YOUR_WRANGLER_NAME.wrangler.dev`

**Comment by shunkakinoki** [comment]
Closing it for just a ref!

**Comment by AdiRishi** [comment]
@shunkakinoki thanks for raising this bug 😄 
It's a good catch, I've been subconsciously doing this the whole time, but it's a big gotcha for anyone setting up the project for the first time.

I've made a PR to document this clearly in the README.
