### ISSUE TITLE
[Bug]: `deleteOldCache` cron fails with more than 1k keys

### ISSUE THREAD

**Issue by colinmcdonald22** [AdiRishi/turborepo-remote-cache-cloudflare#43]
**Describe the bug**
When the `deleteOldCache` cron runs, and there's more than 1k keys to delete, the Worker will fail with the following exception:

```
{
  "Name":"Error",
  "Message":"delete: The number of keys in the request must be between 1 and 1000 inclusive. (10027)",
  "TimestampMs":1692154867482
}
```

This doesn't appear to be documented here https://developers.cloudflare.com/r2/api/workers/workers-api-reference/#bucket-method-definitions, but seems to match the documented 1000 limit for `list`.

**To Reproduce**

1. Create more than 1k keys to be deleted
2. Wait for cron to run

**Expected behavior**
No exceptions would be thrown.

**Comment by AdiRishi** [comment]
@colinmcdonald22 thanks for reporting this!
Didn't realise this was a limitation, especially since it doesn't seem to manifest in miniflare locally at all; curious 🤔 .

Looking at the cron right now, it will likely fall over if there are a huge number of objects, and it will naturally bump up against the limits you saw. I'm working on modifying the cron so it can handle potentially 100,000+ objects, hold tight, fix is coming soon.

**Comment by colinmcdonald22** [comment]
> @colinmcdonald22 thanks for reporting this! Didn't realise this was a limitation, especially since it doesn't seem to manifest in miniflare locally at all; curious 🤔 .
> 
> Looking at the cron right now, it will likely fall over if there are a huge number of objects, and it will naturally bump up against the limits you saw. I'm working on modifying the cron so it can handle potentially 100,000+ objects, hold tight, fix is coming soon.

Sounds good, thank you. For reference here's test code I used to confirm before opening the issue:

```
export interface Env {
  TEST_BUCKET: R2Bucket;
}

export default {
	async fetch(request: Request, env: Env, ctx: ExecutionContext): Promise<Response> {
        	const keys = Array(1005).map((_, idx) => idx.toString());
        	await env.TEST_BUCKET.delete(keys);
        	return new Response('Deleted.');
	}
};
```

and

```
name = "r2-test"
main = "src/worker.ts"
compatibility_date = "2023-08-07"
r2_buckets  = [
  { binding = "TEST_BUCKET", bucket_name = "test-bucket", preview_bucket_name = "test-bucket" }
]
```

This example _does_ work locally (`wrangler dev`), but _does not_ work when actually deployed to Cloudflare

**Comment by AdiRishi** [comment]
> This example does work locally (wrangler dev), but does not work when actually deployed to Cloudflare

Yup I found the same thing. I'll likely raise a few issues in the miniflare and docs repository once I'm done fixing this. Local dev should match prod in an ideal world.

**Comment by AdiRishi** [comment]
@colinmcdonald22 The PR I'm about to merge has been tested with a bucket that contains over 2000 objects. The issue should be resolved once it's merged 👍

**Comment by colinmcdonald22** [comment]
> @colinmcdonald22 The PR I'm about to merge has been tested with a bucket that contains over 2000 objects. The issue should be resolved once it's merged 👍

Perfect, just deployed the new version to our account. Really appreciate the quick response + fix time here! 🎉
