### ISSUE TITLE
[Feature]: Decrease overall bundle size

### ISSUE THREAD

**Issue by AdiRishi** [AdiRishi/turborepo-remote-cache-cloudflare#536]
Current stats - Total Upload: `89.19 KiB / gzip: 25.73 KiB`

Decreasing bundle size has a meaningful impact on performance in Cloudflare Workers. (Serverless runtimes in general)

How can we do this?
- Remove / replace Zod
- Remove / replace Hono

**Comment by AdiRishi** [comment]
This is the current makup of the bundle.

Treemap:
<img width="1393" alt="Screenshot 2024-08-18 at 5 51 46 PM" src="https://github.com/user-attachments/assets/50eb2b0b-6f64-404d-990e-999a552c5950">

Sunburst Chart:
<img width="772" alt="Screenshot 2024-08-18 at 5 53 06 PM" src="https://github.com/user-attachments/assets/46ab3e5a-713f-412b-8a04-258d0c4af78c">

<img width="1267" alt="Screenshot 2024-08-18 at 5 53 19 PM" src="https://github.com/user-attachments/assets/65cd4ed8-4cf2-4783-8c21-7ca48939a23c">

Flame Chart:
<img width="1023" alt="Screenshot 2024-08-18 at 5 53 31 PM" src="https://github.com/user-attachments/assets/10f0dd0e-ac83-4584-8b87-8a720429eeb6">

**Comment by ItsWendell** [comment]
Saw this issue in my feed, something relatively easy to reduce the bundle size could be to use `hono/tiny` (https://hono.dev/docs/api/presets#hono-tiny) and replacing Zod with Valibot (https://valibot.dev/guides/comparison/#comparison-with-zod), which also has a validator for Hono.

**Comment by ItsWendell** [comment]
I ran this through [bundlejs.com - includes config / results?](https://bundlejs.com/?q=github%3Ahttps%3A%2F%2Fraw.githubusercontent.com%2FItsWendell%2Fturborepo-remote-cache-cloudflare%2Fmaster%2Fsrc%2Findex.ts&treeshake=%5B*%5D&config=%7B%22cdn%22%3A%22+https%3A%2F%2Fesm.sh%22%7D) and got result of `Bundle size is 32.4 kB -> 11.2 kB (gzip)`, which is already more than 50/60% decrease. I think the we can decrease this indeed even more by removing hono / vlalibot and writing simple parser / routers ourselves but we'll lose the benefit of readability / maintainability.

**Comment by AdiRishi** [comment]
Hey @ItsWendell , thank you for the PR! 

> Edit: P.s. what tool did you use to annalyze bundle size here?
I ran esbuild manually to bundle the worker (this is what wrangler does internally). I then uploaded the metafile into [esbuild's bundle size analyzer](https://esbuild.github.io/analyze/)
```bash
esbuild src/index.ts --bundle --outfile=out/index.js --minify --external:cloudflare:workers --metafile=out/meta.json
```

I think your PR is a great first step. Switching `zod` to `Valibot` is a great choice, I was thinking the same.

`hono/tiny` is a good intermediate step. I was actually thinking of switching to `itty-router` - https://itty.dev/
Feels more condusive to a small bundle size. Although I'm still trying to evaluate if this is a good decision. We can skip this for now.

Did you want to take the PR through all the way to completion? Very happy to review it and work with you. If not, let me know and I can take over.

**Comment by ItsWendell** [comment]
@AdiRishiHappy to help you bring the PR through completion. Glad you were eyeing valibot too! I don't have a lot of experience with `itty-router`, but at first glance, the DX of hono feels a lot cleaner. Honestly, not sure if switching and rewriting a huge chunk of your code to shave off even more bytes is worth it.
