### ISSUE TITLE
[Bug]: `deleteOldCache` cron fails with 0 keys

### ISSUE THREAD

**Issue by colinmcdonald22** [AdiRishi/turborepo-remote-cache-cloudflare#55]
**Describe the bug**
Back again with the exact same error - but for a different reason!

We're seeing the same error out of the cron: `delete: The number of keys in the request must be between 1 and 1000 inclusive. (10027)`

This time, however, it's because `delete` is being called with an empty array. Specifically, this line: https://github.com/AdiRishi/turborepo-remote-cache-cloudflare/blob/master/src/crons/deleteOldCache.ts#L32 is called when `keysAvailableForDeletion.keys` is `[]`. 

Looks like this is also possible in the second delete block - proper solution would likely be to not push to `keysMarkedForDeletion` if it (`keysForDeletion: R2KeysForDeletion`) doesn't contain any keys. Happy to submit a short PR to do this if 'ya agree.

**To Reproduce**
Run cron when the bucket _doesn't_ contain any items to delete.

**Expected behavior**
No exception is thrown

**Comment by AdiRishi** [comment]
Sigh, can't believe I missed this... 🤦 

Again, great catch 😄 

Yes I'm happy to accept a PR for this, I agree with your solution.

**Comment by colinmcdonald22** [comment]
No worries - I was a bit confused seeing the same error too, thought I hadn't deployed the new version properly

https://github.com/AdiRishi/turborepo-remote-cache-cloudflare/pull/57
