### ISSUE TITLE
[Bug]: Custom remote cache builds cannot be triggered on Vercel

### ISSUE THREAD

**Issue by AdiRishi** [AdiRishi/turborepo-remote-cache-cloudflare#651]
There have been bug reports that this project cannot be used when using Vercel builds for CI.

Reported here - https://github.com/AdiRishi/turborepo-remote-cache-cloudflare/issues/537#issuecomment-2312031280

> I meant to enable the remote cache on Vercel builds.
> Followed your instructions but vercel seems to inject their own teamId overwriting the specified env TURBO_TEAM, disabling access to the cloudflare cache

**Comment by shunkakinoki** [comment]
Thank you so much for the issue @AdiRishi 

Please let me know how can I help 🙇‍♂️

**Comment by AdiRishi** [comment]
Hey @shunkakinoki I spent a bunch of time trying to experiement with this on Vercel. Basically what's happening is that Vercel will override the `TURBO_TOKEN` environment variable.
In my testing, it was making requests to the Cloudflare server, but they are all rejected as the value of TURBO_TOKEN is wrong.

Since that token it injects is a JWT, I doubt you'd be able to save it raw and use it as well.
I've asked about this on the Vercel community forum, lets see what they say - https://vercel.community/t/how-to-stop-vercel-from-injecting-and-overriding-the-turbo-token-env-var/1401

**Comment by AdiRishi** [comment]
@shunkakinoki Vercel has completed their fix for this and I've confirmed it works.
Here's how I had my environment variabels setup when testing on Vercel
<img width="945" alt="Screenshot 2024-10-29 at 5 21 13 PM" src="https://github.com/user-attachments/assets/a3c61134-fdff-49a1-af94-3a629d28ddd0">


Closing this issue now. Feel free to re-open if it doesn't work for you.

**Comment by shunkakinoki** [comment]
@AdiRishi Thank you so much for your tireless work - appreciate digging into this 🙏
